# Generated by Django 4.2.3 on 2025-04-27 05:35
from django.db import migrations


import logging


def cargar_datos(apps, schema_editor):
    logging.info('Iniciando carga de datos')
    Autor = apps.get_model('libros_api', 'Autor')
    Libro = apps.get_model('libros_api', 'Libro')

    # Crear Autores
    autor1 = Autor.objects.create(nombre='Gabriel', apellido='García Márquez')
    logging.info('Autor creado: Gabriel García Márquez')
    autor2 = Autor.objects.create(nombre='Isabel', apellido='Allende')
    logging.info('Autor creado: Isabel Allende')
    autor3 = Autor.objects.create(nombre='Jorge Luis', apellido='Borges')
    logging.info('Autor creado: Jorge Luis Borges')
    autor4 = Autor.objects.create(nombre='Julio', apellido='Cortázar')
    logging.info('Autor creado: Julio Cortázar')

    # Crear Libros
    libro1 = Libro.objects.create(
        titulo='Cien años de soledad', fecha_publicacion='1967-05-30', isbn='9780307350438')
    logging.info('Libro creado: Cien años de soledad')
    libro1.autores.add(autor1)
    logging.info(
        'Autor agregado a libro: Gabriel García Márquez - Cien años de soledad')

    libro2 = Libro.objects.create(
        titulo='La casa de los espíritus', fecha_publicacion='1982-01-01', isbn='9788401343038')
    logging.info('Libro creado: La casa de los espíritus')
    libro2.autores.add(autor2)
    logging.info(
        'Autor agregado a libro: Isabel Allende - La casa de los espíritus')

    libro3 = Libro.objects.create(
        titulo='Ficciones', fecha_publicacion='1944-01-01', isbn='9788420674032')
    logging.info('Libro creado: Ficciones')
    libro3.autores.add(autor3)
    logging.info('Autor agregado a libro: Jorge Luis Borges - Ficciones')

    libro4 = Libro.objects.create(
        titulo='Rayuela', fecha_publicacion='1963-06-28', isbn='9788466348868')
    logging.info('Libro creado: Rayuela')
    libro4.autores.add(autor4)
    logging.info('Autor agregado a libro: Julio Cortázar - Rayuela')

    # Libro con múltiples autores (ejemplo)
    libro_colab = Libro.objects.create(
        titulo='Antología del cuento fantástico', fecha_publicacion='1940-01-01', isbn='9789500398660')
    logging.info('Libro creado: Antología del cuento fantástico')
    libro_colab.autores.add(autor3, autor4)  # Agregamos a Borges y Cortázar
    logging.info(
        'Autores agregados a libro: Jorge Luis Borges y Julio Cortázar - Antología del cuento fantástico')
    logging.info('Carga de datos finalizada')


def eliminar_datos(apps, schema_editor):
    # Opcional: Código para revertir los datos si deshaces la migración
    Autor = apps.get_model('libros_api', 'Autor')
    Libro = apps.get_model('libros_api', 'Libro')
    Libro.objects.filter(isbn__in=['9780307350438', '9788401343038',
                                   '9788420674032', '9788466348868', '9789500398660']).delete()
    Autor.objects.filter(
        apellido__in=['García Márquez', 'Allende', 'Borges', 'Cortázar']).delete()


class Migration(migrations.Migration):

    dependencies = [
        # Asegúrate que dependa de la migración anterior
        ('libros_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(cargar_datos, reverse_code=eliminar_datos),
    ]
